---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: /home/vagrant/spring-petclinic-2.6.0-SNAPSHOT.jar
        dest: /home/ubuntu
...